replicaCount: 2

image:
  repository: nikanuna/flask-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "15m"
    memory: "750Mi"
  limits:
    cpu: "15m"
    memory: "750Mi"
